#!/bin/bash

# Update Git submodules
git submodule update --init

# Install Python packages using pippip install

 flask flask_cors bs4 lxml pelican markdown geventpip install flask flask_cors bs4 lxml pelican markdown gevent


# Optionally, you can add more commands or customizations here.pip install flask flask_cors bs4 lxml pelican markdown gevent