#!/bin/bash

# Update Git submodules
git submodule update --init

# Install Python packages using pippip install

 flask flask_cors bs4 lxml pelican markdown gevent
 flask flask_cors bs4 lxml pelican markdown geventpip install

# Optionally, you can add more commands or customizations here.pip install flask flask_cors bs4 lxml pelican markdown gevent